name: Python-CI

on:
  - push
  - pull_request

jobs:
  make_depends:
    runs-on: ubuntu-latest
    steps:
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          make install
          make lint-install

  make_testing:
    runs-on: ubuntu-latest
    needs: [make_depends]
    steps:
      - name: Run linter and pytest
        run: |
          make lint
